
-- --------------------------------------------------------

--
-- Table structure for table `log_error`
--

CREATE TABLE `log_error` (
  `ID` int(11) NOT NULL,
  `User` varchar(100) DEFAULT NULL,
  `Severity` enum('Information','Warning','Error','Critical','High') NOT NULL DEFAULT 'Error',
  `ErrorType` varchar(100) DEFAULT NULL,
  `ErrorMessage` text NOT NULL,
  `StackTrace` text,
  `ModuleName` varchar(200) DEFAULT NULL,
  `MethodName` varchar(200) DEFAULT NULL,
  `AdditionalInfo` text,
  `MachineName` varchar(100) DEFAULT NULL,
  `OSVersion` varchar(100) DEFAULT NULL,
  `AppVersion` varchar(50) DEFAULT NULL,
  `ErrorTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Truncate table before insert `log_error`
--

TRUNCATE TABLE `log_error`;
--
-- Dumping data for table `log_error`
--

INSERT INTO `log_error` (`ID`, `User`, `Severity`, `ErrorType`, `ErrorMessage`, `StackTrace`, `ModuleName`, `MethodName`, `AdditionalInfo`, `MachineName`, `OSVersion`, `AppVersion`, `ErrorTime`) VALUES
(4, 'JOHNK', 'Error', 'DatabaseError', 'inv_inventory_Add_Item failed: Unknown column \'Location\' in \'field list\'', 'Unknown column \'Location\' in \'field list\'', 'inv_inventory_Add_Item', 'Add_Item', 'PartID=01-33371-000; Location=CS-02; Operation=100; Qty=30', 'Database Server', 'MySQL 5.7.24', '5.0.1.2', '2025-08-13 21:43:50'),
(5, 'JOHNK', 'Error', 'DatabaseError', 'inv_inventory_Add_Item failed: Unknown column \'Location\' in \'field list\'', 'Unknown column \'Location\' in \'field list\'', 'inv_inventory_Add_Item', 'Add_Item', 'PartID=01-33371-000; Location=CS-02; Operation=100; Qty=30', 'Database Server', 'MySQL 5.7.24', '5.0.1.2', '2025-08-13 21:44:30'),
(6, 'JOHNK', 'Error', 'DatabaseError', 'inv_inventory_Add_Item failed: Unknown column \'Location\' in \'field list\'', 'Unknown column \'Location\' in \'field list\'', 'inv_inventory_Add_Item', 'Add_Item', 'PartID=01-33371-000; Location=CS-02; Operation=100; Qty=30', 'Database Server', 'MySQL 5.7.24', '5.0.1.2', '2025-08-13 21:44:32'),
(7, 'BAUSTIN', 'Error', 'DatabaseError', 'inv_inventory_Remove_Item failed: Unknown column \'Location\' in \'field list\'', 'Unknown column \'Location\' in \'field list\'', 'inv_inventory_Remove_Item', 'Remove_Item', 'PartID=21-28841-007; Batch=0000000886; Qty=5', 'Database Server', 'MySQL 5.7.24', '5.0.1.2', '2025-08-13 21:48:57'),
(8, 'BAUSTIN', 'Error', 'DatabaseError', 'inv_inventory_Remove_Item failed: Unknown column \'Location\' in \'field list\'', 'Unknown column \'Location\' in \'field list\'', 'inv_inventory_Remove_Item', 'Remove_Item', 'PartID=21-28841-007; Batch=0000000886; Qty=5', 'Database Server', 'MySQL 5.7.24', '5.0.1.2', '2025-08-13 21:48:59'),
(9, 'BAUSTIN', 'Error', 'DatabaseError', 'inv_inventory_Remove_Item failed: Unknown column \'Location\' in \'field list\'', 'Unknown column \'Location\' in \'field list\'', 'inv_inventory_Remove_Item', 'Remove_Item', 'PartID=21-28841-007; Batch=0000000886; Qty=5', 'Database Server', 'MySQL 5.7.24', '5.0.1.2', '2025-08-13 21:49:00'),
(12, 'JOHNK', 'Error', 'System.Exception', 'Failed to retrieve inventory for part 01-33371-000, operation 100: An error occurred while executing inv_inventory_Get_ByPartIDAndOperation: Procedure or function \'inv_inventory_Get_ByPartIDAndOperation\' cannot be found in database \'\' Verify that user \'JOHNK\'@\'localhost\' has enough privileges to execute', '   at MTM_Inventory_Application.Controls.MainForm.Control_RemoveTab.Control_RemoveTab_Button_Search_Click(Object sender, EventArgs e) in C:\\Users\\johnk\\source\\repos\\MTM_WIP_Application\\Controls\\MainForm\\Control_RemoveTab.cs:line 715', '', 'Control_RemoveTab_Button_Search_Click', '', 'JOHNSPC', 'Microsoft Windows NT 10.0.26100.0', '5.0.1.2+91049c6b3801a10d0c40ce5d02b8fb94042bc088', '2025-08-14 00:20:17'),
(13, 'JOHNK', 'Error', 'MySql.Data.MySqlClient.MySqlException', 'Procedure or function \'inv_transactions_Search\' cannot be found in database \'\' Verify that user \'DEFAULT\'@\'localhost\' has enough privileges to execute', '   at MySql.Data.MySqlClient.ProcedureCache.GetProcDataAsync(MySqlConnection connection, String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.ProcedureCache.AddNewAsync(MySqlConnection connection, String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.ProcedureCache.GetProcedureAsync(MySqlConnection conn, String spName, String cacheKey, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.GetParametersAsync(String procName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.CheckParametersAsync(String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.Resolve(Boolean preparing)\r\n   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)\r\n   at MTM_Inventory_Application.Helpers.Helper_Database_StoredProcedure.ExecuteReader(String connectionString, String procedureName, Dictionary`2 parameters, Boolean useAsync, CommandType commandType) in C:\\Users\\johnk\\source\\repos\\MTM_WIP_Application\\Helpers\\Helper_Database_StoredProcedure.cs:line 231\r\n   at MTM_Inventory_Application.Data.Dao_Transactions.SearchTransactionsAsync(String userName, Boolean isAdmin, String partID, String batchNumber, String fromLocation, String toLocation, String operation, Nullable`1 transactionType, Nullable`1 quantity, String notes, String itemType, Nullable`1 fromDate, Nullable`1 toDate, String sortColumn, Boolean sortDescending, Int32 page, Int32 pageSize) in C:\\Users\\johnk\\source\\repos\\MTM_WIP_Application\\Data\\Dao_Transactions.cs:line 82', '', 'SearchTransactionsAsync', '', 'JOHNSPC', 'Microsoft Windows NT 10.0.26100.0', '5.0.1.2+224e717e5860cafb155b2fe07d0abceecd571a48', '2025-08-14 00:56:51'),
(14, 'JOHNK', 'Error', 'MySql.Data.MySqlClient.MySqlException', 'Procedure or function \'inv_transactions_Search\' cannot be found in database \'\' Verify that user \'DEFAULT\'@\'localhost\' has enough privileges to execute', '   at MySql.Data.MySqlClient.ProcedureCache.GetProcDataAsync(MySqlConnection connection, String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.ProcedureCache.AddNewAsync(MySqlConnection connection, String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.ProcedureCache.GetProcedureAsync(MySqlConnection conn, String spName, String cacheKey, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.GetParametersAsync(String procName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.CheckParametersAsync(String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.Resolve(Boolean preparing)\r\n   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)\r\n   at MTM_Inventory_Application.Helpers.Helper_Database_StoredProcedure.ExecuteReader(String connectionString, String procedureName, Dictionary`2 parameters, Boolean useAsync, CommandType commandType) in C:\\Users\\johnk\\source\\repos\\MTM_WIP_Application\\Helpers\\Helper_Database_StoredProcedure.cs:line 231\r\n   at MTM_Inventory_Application.Data.Dao_Transactions.SearchTransactionsAsync(String userName, Boolean isAdmin, String partID, String batchNumber, String fromLocation, String toLocation, String operation, Nullable`1 transactionType, Nullable`1 quantity, String notes, String itemType, Nullable`1 fromDate, Nullable`1 toDate, String sortColumn, Boolean sortDescending, Int32 page, Int32 pageSize) in C:\\Users\\johnk\\source\\repos\\MTM_WIP_Application\\Data\\Dao_Transactions.cs:line 82', '', 'SearchTransactionsAsync', '', 'JOHNSPC', 'Microsoft Windows NT 10.0.26100.0', '5.0.1.2+224e717e5860cafb155b2fe07d0abceecd571a48', '2025-08-14 00:57:08'),
(15, 'JOHNK', 'Error', 'MySql.Data.MySqlClient.MySqlException', 'Procedure or function \'inv_transactions_Search\' cannot be found in database \'\' Verify that user \'DEFAULT\'@\'localhost\' has enough privileges to execute', '   at MySql.Data.MySqlClient.ProcedureCache.GetProcDataAsync(MySqlConnection connection, String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.ProcedureCache.AddNewAsync(MySqlConnection connection, String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.ProcedureCache.GetProcedureAsync(MySqlConnection conn, String spName, String cacheKey, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.GetParametersAsync(String procName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.CheckParametersAsync(String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.Resolve(Boolean preparing)\r\n   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)\r\n   at MTM_Inventory_Application.Helpers.Helper_Database_StoredProcedure.ExecuteReader(String connectionString, String procedureName, Dictionary`2 parameters, Boolean useAsync, CommandType commandType) in C:\\Users\\johnk\\source\\repos\\MTM_WIP_Application\\Helpers\\Helper_Database_StoredProcedure.cs:line 231\r\n   at MTM_Inventory_Application.Data.Dao_Transactions.SearchTransactionsAsync(String userName, Boolean isAdmin, String partID, String batchNumber, String fromLocation, String toLocation, String operation, Nullable`1 transactionType, Nullable`1 quantity, String notes, String itemType, Nullable`1 fromDate, Nullable`1 toDate, String sortColumn, Boolean sortDescending, Int32 page, Int32 pageSize) in C:\\Users\\johnk\\source\\repos\\MTM_WIP_Application\\Data\\Dao_Transactions.cs:line 82', '', 'SearchTransactionsAsync', '', 'JOHNSPC', 'Microsoft Windows NT 10.0.26100.0', '5.0.1.2+39c6941734210f189b1a87a16cc629a779791448', '2025-08-14 00:59:14'),
(16, 'JOHNK', 'Error', 'MySql.Data.MySqlClient.MySqlException', 'Procedure or function \'inv_transactions_Search\' cannot be found in database \'\' Verify that user \'DEFAULT\'@\'localhost\' has enough privileges to execute', '   at MySql.Data.MySqlClient.ProcedureCache.GetProcDataAsync(MySqlConnection connection, String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.ProcedureCache.AddNewAsync(MySqlConnection connection, String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.ProcedureCache.GetProcedureAsync(MySqlConnection conn, String spName, String cacheKey, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.GetParametersAsync(String procName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.CheckParametersAsync(String spName, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.StoredProcedure.Resolve(Boolean preparing)\r\n   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)\r\n   at MTM_Inventory_Application.Helpers.Helper_Database_StoredProcedure.ExecuteReader(String connectionString, String procedureName, Dictionary`2 parameters, Boolean useAsync, CommandType commandType) in C:\\Users\\johnk\\source\\repos\\MTM_WIP_Application\\Helpers\\Helper_Database_StoredProcedure.cs:line 231\r\n   at MTM_Inventory_Application.Data.Dao_Transactions.SearchTransactionsAsync(String userName, Boolean isAdmin, String partID, String batchNumber, String fromLocation, String toLocation, String operation, Nullable`1 transactionType, Nullable`1 quantity, String notes, String itemType, Nullable`1 fromDate, Nullable`1 toDate, String sortColumn, Boolean sortDescending, Int32 page, Int32 pageSize) in C:\\Users\\johnk\\source\\repos\\MTM_WIP_Application\\Data\\Dao_Transactions.cs:line 82', '', 'SearchTransactionsAsync', '', 'JOHNSPC', 'Microsoft Windows NT 10.0.26100.0', '5.0.1.2+39c6941734210f189b1a87a16cc629a779791448', '2025-08-14 00:59:14');
