name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore MTM_WIP_Application.sln
      
    - name: Build
      run: dotnet build MTM_WIP_Application.sln --no-restore --configuration Release
      
    - name: Test
      run: dotnet test tests/MTM_WIP_Application.UnitTests.csproj --no-build --configuration Release --verbosity normal
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: tests/TestResults/
        
  code-quality:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore MTM_WIP_Application.sln
      
    - name: Build
      run: dotnet build MTM_WIP_Application.sln --no-restore --configuration Release
      
    - name: Run Code Analysis
      run: dotnet build MTM_WIP_Application.sln --verbosity normal /p:RunAnalyzersDuringBuild=true
      
    - name: Check Format
      run: dotnet format MTM_WIP_Application.sln --verbosity normal --verify-no-changes